In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# x1에 공부한 시간 부여
# x2에 출석일수 부여
# 레이블(y), 점수

x1 = tf.constant( [1,0,3,0,5], tf.float32 ) 
x2 = tf.constant( [0,2,3,4,5], tf.float32 )
y = tf.constant( [1,2,3,4,5], tf.float32 )

In [3]:
w1 = tf.Variable( tf.random_uniform([1]) )
w2 = tf.Variable( tf.random_uniform([1]) )
b = tf.Variable( tf.random_uniform([1]) )

In [5]:
hx = w1*x1 + w2*x2 + b
cost = tf.reduce_mean( tf.square(hx-y) )

In [6]:
optimizer = tf.train.GradientDescentOptimizer( 0.1 ) # argument로 learning mate를 투입
train = optimizer.minimize( cost )

In [7]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
for i in range(100) :
    # place holder로 지정한 것 없으므로 feed_dict 줄 것 없이 바로 run, training
    sess.run( train )
    print( i, sess.run(cost) )

0 5.245378
1 4.937807
2 4.650161
3 4.3811316
4 4.129504
5 3.8941388
6 3.6739712
7 3.4680061
8 3.2753167
9 3.0950313
10 2.9263413
11 2.7684867
12 2.6207604
13 2.4824986
14 2.3530831
15 2.2319362
16 2.1185174
17 2.0123208
18 1.9128755
19 1.8197399
20 1.7325033
21 1.6507794
22 1.5742081
23 1.5024548
24 1.4352038
25 1.372162
26 1.3130548
27 1.2576256
28 1.2056351
29 1.1568599
30 1.1110898
31 1.0681293
32 1.0277961
33 0.9899193
34 0.9543389
35 0.92090636
36 0.8894819
37 0.8599353
38 0.83214444
39 0.8059968
40 0.7813849
41 0.7582096
42 0.7363783
43 0.7158042
44 0.6964058
45 0.67810744
46 0.66083854
47 0.6445326
48 0.62912834
49 0.61456716
50 0.60079545
51 0.58776253
52 0.5754215
53 0.5637277
54 0.55264056
55 0.5421208
56 0.53213286
57 0.5226429
58 0.5136194
59 0.50503314
60 0.4968563
61 0.48906344
62 0.4816305
63 0.474535
64 0.4677558
65 0.46127337
66 0.4550694
67 0.44912642
68 0.4434288
69 0.43796143
70 0.43271008
71 0.42766184
72 0.42280442
73 0.4181262
74 0.41361666
75 0.40926567
76 0.405

In [9]:
# w1 확인
sess.run(w1)

array([0.37121424], dtype=float32)

In [11]:
# w2 확인
sess.run(w2)

array([0.6691739], dtype=float32)

In [12]:
# bias 확인
sess.run(b)

array([0.32804543], dtype=float32)