In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 정규화
from sklearn import preprocessing   # 전처리

# 방법 1

In [2]:
# 0~ 3번지 컬럼 / 4번지 컬럼
# 0~3번째까지 feature
# 맨 마지막은 레이블
 
data = [[828, 920, 1234567, 1020, 1111],

        [824, 910, 2345612, 1090, 1234],

        [880, 900, 3456123, 1010, 1000],

        [870, 990, 2312123, 1001, 1122],

        [860, 980, 3223123, 1008, 1133],

        [850, 970, 2432123, 1100, 1221]]

data = np.float32(data)

In [3]:
# 0:4 
# 0<= column <4 
# 0:-1
# 0 <= column <-1

xdata = data[:,:-1]
ydata = data[:,[-1]]

In [4]:
ydata

array([[1111.],
       [1234.],
       [1000.],
       [1122.],
       [1133.],
       [1221.]], dtype=float32)

In [5]:
# feature의 개수가 4개

x = tf.placeholder( tf.float32 , shape =[None,4]) #---------> n행 3열 행렬

y = tf.constant( ydata, tf.float32)

In [6]:
# feature의 개수 4개 

w = tf.Variable( tf.random_uniform([4,1]))
b = tf.Variable( tf.random_uniform([1]))

In [7]:
hx = tf.matmul( x,w ) + b    # n x 4 행렬   +      4 x 1 행렬    => n x 1 행렬

cost = tf.reduce_mean(tf.square(hx-y))

In [8]:
# argument로 learning mate를 투입, 정규화를 위해 매우 작은 값 투입
optimizer = tf.train.AdamOptimizer( 0.0001 ) 

train = optimizer.minimize( cost )

In [9]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [10]:
# 트레이닝
for i in range(10000) :
    # x가 placeholder이므로 feed_dict 줘야 함
    sess.run( train, {x:xdata} )
    print(i, sess.run(cost, {x:xdata}))

0 2403457800000.0
1 2402650000000.0
2 2401842500000.0
3 2401035000000.0
4 2400227700000.0
5 2399420800000.0
6 2398613700000.0
7 2397807300000.0
8 2397000400000.0
9 2396194000000.0
10 2395388000000.0
11 2394582200000.0
12 2393776300000.0
13 2392970800000.0
14 2392165400000.0
15 2391360100000.0
16 2390555000000.0
17 2389750000000.0
18 2388945300000.0
19 2388140200000.0
20 2387335700000.0
21 2386531500000.0
22 2385726700000.0
23 2384923200000.0
24 2384119500000.0
25 2383316000000.0
26 2382512800000.0
27 2381709600000.0
28 2380906400000.0
29 2380103700000.0
30 2379300700000.0
31 2378498300000.0
32 2377696100000.0
33 2376894300000.0
34 2376092600000.0
35 2375291000000.0
36 2374489300000.0
37 2373688000000.0
38 2372886600000.0
39 2372085700000.0
40 2371285200000.0
41 2370484800000.0
42 2369684800000.0
43 2368884400000.0
44 2368084600000.0
45 2367284800000.0
46 2366485300000.0
47 2365685800000.0
48 2364886700000.0
49 2364088000000.0
50 2363289500000.0
51 2362491000000.0
52 2361692800000.0
53 

In [11]:
# 결과 Nan에 대한 해결책

# 1. 러닝메이트 값을 매우 작게 주는 방법   -> 비 추천
# 2. optimizer를 바꾸는 방법 - Adam 사용  -> 추천
# 3. normalize (정규화)                  -> 가장 추천

# normalization
# (X - Xmin) / (Xmax - Xmin)


# standardization
# 표준화
# (X - 평균) / 표준편차

# 방법 2

In [12]:
scale = preprocessing.MinMaxScaler()
dataN = scale.fit_transform( data )

In [13]:
# 0에서 1까지의 값으로 변경됨
# normalization 수행
dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933, 0.47435904],
       [0.        , 0.11111164, 0.50012016, 0.89899063, 1.0000005 ],
       [1.        , 0.        , 1.        , 0.09090996, 0.        ],
       [0.8214283 , 1.        , 0.48504567, 0.        , 0.52136755],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732, 0.56837654],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        , 0.94444466]],
      dtype=float32)

In [14]:
xdata =  dataN[:,:-1]
ydata = dataN[:,[-1]]

# feature의 개수가 4개

x = tf.placeholder( tf.float32 , shape =[None,4]) #---------> n행 4열 행렬
y = tf.constant( ydata, tf.float32)

w = tf.Variable( tf.random_uniform([4,1]))
b = tf.Variable( tf.random_uniform([1]))

hx = tf.matmul( x,w ) + b    # n x 4 행렬   +      4 x 1 행렬    => n x 1 행렬
cost = tf.reduce_mean(tf.square(hx-y))

In [15]:
optimizer = tf.train.GradientDescentOptimizer( 0.00001 ) 

train = optimizer.minimize( cost )

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(10000) :
    # x가 placeholder이므로 feed_dict 줘야 함
    sess.run( train, {x:xdata} )
    print(i, sess.run(cost, {x:xdata}))

0 0.52479017
1 0.5247612
2 0.5247323
3 0.5247032
4 0.52467436
5 0.5246453
6 0.5246164
7 0.52458745
8 0.5245585
9 0.52452946
10 0.5245006
11 0.52447164
12 0.52444273
13 0.5244137
14 0.5243848
15 0.5243558
16 0.5243269
17 0.52429795
18 0.524269
19 0.52424
20 0.5242111
21 0.52418214
22 0.5241533
23 0.5241243
24 0.52409536
25 0.52406645
26 0.52403754
27 0.5240086
28 0.5239797
29 0.52395076
30 0.5239218
31 0.5238929
32 0.5238639
33 0.52383506
34 0.52380615
35 0.5237772
36 0.5237484
37 0.5237194
38 0.5236904
39 0.5236616
40 0.52363265
41 0.5236038
42 0.5235749
43 0.5235459
44 0.5235171
45 0.5234881
46 0.5234593
47 0.5234303
48 0.52340144
49 0.5233726
50 0.5233436
51 0.5233147
52 0.5232859
53 0.52325696
54 0.52322817
55 0.5231992
56 0.52317035
57 0.52314156
58 0.5231126
59 0.5230837
60 0.5230549
61 0.52302593
62 0.5229972
63 0.52296823
64 0.52293926
65 0.5229105
66 0.52288157
67 0.52285284
68 0.52282387
69 0.52279496
70 0.52276623
71 0.5227373
72 0.5227085
73 0.5226796
74 0.52265066
75 0.5226

In [16]:
# weight
sess.run(w)

array([[ 0.6113575 ],
       [-0.03202181],
       [-0.03032778],
       [ 0.20928992]], dtype=float32)

In [17]:
# bias
sess.run(b)

array([0.5907093], dtype=float32)

In [18]:
# 예측할 데이터 : [828, 920, 1234567, 1020]

# sess.run( hx, {x:[[828, 920, 1234567, 1020]]}) 
# 이 데이터를 그대로 줄 수 없음(정규화했기 때문에)

In [19]:
# scale개체를 이용
# scale.transform([[828, 920, 1234567, 1020]])
# 4개짜리 -> 에러가 나옴 
# 데이터를 전부 정규화 시켰기 때문에



# 5개짜리에 대해서만 정규화 할 수 있음
# None으로 개수 맞춰줌

arr = scale.transform([[828, 920, 1234567, 1020, None]])

# 슬라이싱
arr[:, :-1]

array([[7.14281425e-02, 2.22222470e-01, 1.00739044e-08, 1.91919606e-01]])

In [20]:
# 예측
sess.run(hx, {x:arr[:, :-1]})

# 결과값이 정규화된 값이므로 역정규화를 시켜야 함

array([[0.6674283]], dtype=float32)

In [27]:
# 역 정규화된 값
f = scale.inverse_transform([[None,None,None,None,0.5441524]])
f

# 문제점!!!!! 컬럼이 많아지면 매우 불편함

array([[          nan,           nan,           nan,           nan,
        1127.33160214]])

In [22]:
# 매트릭스이므로
f[:, -1]

array([1127.33160214])

In [28]:
# 한개의 컬럼만 준 것
# 컬럼이 많을 경우 이 방법이 유리

labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform(data[:,[-1]] )
y1

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [24]:
aa = sess.run(hx, {x:arr[:,:-1]} )

In [25]:
aa

array([[0.6674283]], dtype=float32)

In [26]:
# 역정규화
labelScale.inverse_transform(aa)

array([[1156.1782]], dtype=float32)