In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 합격 불합격 예측

In [2]:
# x : [공부한 시간, 출석일수]

xdata = [[1,3], [2,2], [3,1], [4,6], [5,5], [6,4]]
ydata = [[0], [0], [0], [1], [1], [1]] # 0이면 불합격, 1이면 합격

In [3]:
x = tf.placeholder( tf.float32, shape=[None,2])
y = tf.constant( ydata, tf.float32)

In [4]:
w = tf.Variable( tf.random_uniform([2,1]) )
b = tf.Variable( tf.random_uniform([1]) )

In [5]:
# z는 연속된 데이터
z = tf.matmul(x,w) + b

# sigmoid 통과하면 0과 1로 도출됨
hx = tf.nn.sigmoid( z ) # 0~1사이의 값

로지스틱 버그 수정

In [23]:
# tensor에서 로그 함수 제공
# 오타 유의


cost = tf.reduce_mean( cost_i )

cost_i = tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)
# 시그모이드와 cost_i 함수가 포함됨 
# 참고 softmax cross entropy
# cost_i = y*(-tf.log(hx)) + (1-y)*(-tf.log(1-hx))

In [24]:
optimizer = tf.train.AdamOptimizer( 0.1 ) 
train = optimizer.minimize( cost )

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [25]:
for i in range(1000) :
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 0.86084944
1 0.70521945
2 0.63017327
3 0.65990275
4 0.71316296
5 0.7112782
6 0.66570604
7 0.609837
8 0.5684237
9 0.5494672
10 0.54675466
11 0.5491689
12 0.54808897
13 0.53951627
14 0.5233042
15 0.5018183
16 0.47876534
17 0.4581152
18 0.44289637
19 0.43393588
20 0.42923173
21 0.4248822
22 0.41740528
23 0.40573213
24 0.3913764
25 0.37700805
26 0.36475143
27 0.35529217
28 0.3480061
29 0.34165144
30 0.33506402
31 0.32756752
32 0.31907648
33 0.30998313
34 0.30092695
35 0.29252687
36 0.2851489
37 0.27878085
38 0.2730694
39 0.26751125
40 0.26170433
41 0.2555216
42 0.24911869
43 0.24279779
44 0.23683184
45 0.2313488
46 0.22631365
47 0.22158547
48 0.21699907
49 0.21243228
50 0.20783854
51 0.20324421
52 0.19872208
53 0.19435394
54 0.19019759
55 0.18626781
56 0.18253654
57 0.17894922
58 0.17544936
59 0.17199947
60 0.1685911
61 0.16524048
62 0.16197565
63 0.15882157
64 0.15579025
65 0.1528784
66 0.15007104
67 0.14734869
68 0.14469437
69 0.14209774
70 0.13955621
71 0.13707335
72 0.13465543
73 0.1

In [26]:
sess.run(w)

array([[1.9828795],
       [1.9868778]], dtype=float32)

In [27]:
sess.run(b)

array([-13.473102], dtype=float32)

In [28]:
result = sess.run(hx, {x:[[3,5]]})

In [29]:
result > 0.5

array([[ True]])

In [30]:
# cast함수 : true인 경우 1, false인 경우 0으로 출력

t = tf.cast( result > 0.5, dtype=tf.int32 )
sess.run(t)

array([[1]])

In [31]:
# 전체 데이터 예측; x:6x2 *(matmul)* w:2x1 -> 6x1 행렬

h = sess.run(hx, {x:xdata})
h

array([[0.00395194],
       [0.00393623],
       [0.00392059],
       [0.9983072 ],
       [0.9983005 ],
       [0.9982937 ]], dtype=float32)

In [32]:
ydata

[[0], [0], [0], [1], [1], [1]]

In [33]:
(h > 0.5) == ydata
# True는 1, False는 0이므로  

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [34]:
((h > 0.5) == ydata).mean() # 정확도를 의미 => 1.0 = 100퍼센트

1.0

In [35]:
h

array([[0.00395194],
       [0.00393623],
       [0.00392059],
       [0.9983072 ],
       [0.9983005 ],
       [0.9982937 ]], dtype=float32)

In [36]:
# y가 float로 되어 있음

predict = tf.cast(h>0.5, dtype = tf.float32)

# sess.run(predict)
e = tf.equal(predict, y) # predict == y랑 같다

m = tf.reduce_mean( tf.cast(e, dtype=tf.float32))

sess.run(m) # 1.0 -> 예측값 100퍼센트

1.0

In [37]:
predict = tf.cast(h>0.5, dtype = tf.float32)

m = tf.reduce_mean( tf.cast(tf.equal(predict, y), dtype=tf.float32))

sess.run(m) # 1.0 -> 예측값 100퍼센트

1.0

In [38]:
sess.run(predict)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)