In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam 

In [2]:
arr = np.loadtxt('data/softmax.txt')
arr

array([[1., 2., 1., 0., 0., 1.],
       [1., 3., 2., 0., 0., 1.],
       [1., 3., 4., 0., 0., 1.],
       [1., 5., 5., 0., 1., 0.],
       [1., 7., 5., 0., 1., 0.],
       [1., 2., 5., 0., 1., 0.],
       [1., 6., 6., 1., 0., 0.],
       [1., 7., 7., 1., 0., 0.]])

In [3]:
xdata = arr[:, 1:3]
xdata

array([[2., 1.],
       [3., 2.],
       [3., 4.],
       [5., 5.],
       [7., 5.],
       [2., 5.],
       [6., 6.],
       [7., 7.]])

In [4]:
ydata = arr[:, 3:]
ydata

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [5]:
x = tf.placeholder(tf.float32, [None,2])
y = tf.constant(ydata, tf.float32)

In [6]:
w = tf.Variable(tf.random_uniform([2,3])) # [f개수, 분류3]
b = tf.Variable(tf.random_uniform([3])) # 분류의 개수

In [15]:
z = tf.matmul(x,w) + b
hx = tf.nn.softmax( z ) # nn안에 함수가 내장


cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=z, labels=y) 
# 로그함수가 내장; softmax + 로그이용한 cost함수 ; 사실 hx가 의미 없음; softmax + crossentropy가 통째로

cost = tf.reduce_mean(cost_i)

In [9]:
optimizer = tf.train.GradientDescentOptimizer(0.1) # argument로 learning mate를 투입
train = optimizer.minimize( cost )
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [10]:
for i in range(1000) :
    sess.run(train, {x:xdata})
    print(i, sess.run(cost, {x:xdata}))

0 1.2455611
1 1.190363
2 1.1653806
3 1.1466914
4 1.1320767
5 1.1189934
6 1.107187
7 1.0961514
8 1.0857863
9 1.0759456
10 1.066581
11 1.0576359
12 1.0490831
13 1.0408932
14 1.033047
15 1.0255244
16 1.0183098
17 1.0113869
18 1.0047414
19 0.9983593
20 0.99222744
21 0.98633283
22 0.9806632
23 0.97520685
24 0.9699527
25 0.96488965
26 0.9600077
27 0.955297
28 0.95074815
29 0.94635254
30 0.9421016
31 0.93798757
32 0.9340029
33 0.93014055
34 0.92639387
35 0.92275643
36 0.9192228
37 0.915787
38 0.9124439
39 0.9091886
40 0.9060167
41 0.9029237
42 0.8999057
43 0.89695877
44 0.8940793
45 0.8912642
46 0.8885102
47 0.8858144
48 0.8831737
49 0.8805861
50 0.8780488
51 0.87555945
52 0.8731162
53 0.8707169
54 0.8683597
55 0.8660428
56 0.8637642
57 0.86152303
58 0.8593173
59 0.8571458
60 0.85500705
61 0.85289997
62 0.8508234
63 0.8487762
64 0.8467573
65 0.8447658
66 0.8428006
67 0.84086114
68 0.8389463
69 0.8370553
70 0.8351875
71 0.8333423
72 0.83151877
73 0.8297165
74 0.82793474
75 0.82617295
76 0.8244

In [18]:
sess.run(w)
# w X x

array([[ 0.6576067 ,  0.5189446 ,  0.37359554],
       [ 1.2765518 ,  0.6448012 , -0.5005687 ]], dtype=float32)

In [12]:
sess.run(b)

array([-4.074282  ,  0.39336476,  5.422378  ], dtype=float32)

In [16]:
sess.run(hx, {x:[[6,6]]})

array([[0.5226701 , 0.44769892, 0.02963097]], dtype=float32)

x : 1x2  +     w: 2x3       => 1x3

In [17]:
sess.run(z, {x:[[6,6]]})

array([[7.5306697, 7.37584  , 4.660539 ]], dtype=float32)

In [37]:
h = sess.run(hx, {x:[[6,6]]})
int(h.argmax(axis=1)) # => 로우별로 가장 큰 값의 인덱스

0

In [36]:
grade = ['A', 'B', 'C']
grade[int(h.argmax(axis=1))]

'A'

In [43]:
# 공부한 시간과 출석일수가 6,6 / 1,1 인 경우 학점
hh = sess.run(hx, {x:[[6,6], [1,1]]})
hh.argmax(axis = 1)

array([0, 2], dtype=int64)

In [44]:
# hx를 z로 구해도 똑같이 나온다
hh = sess.run(z, {x:[[6,6], [1,1]]})
hh.argmax(axis = 1)       # 로우별로 --> 0 : A학점 / 2 : C학점

array([0, 2], dtype=int64)

=======================================================================================================

In [29]:
myarr = np.array([[1,2,3],[3,4,5]])
myarr

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
myarr.argmax() # axis가 없으면 default값으로 1차원으로 풀어버림 -> [1,2,3,3,4,5]

In [32]:
myarr.sum()

18

In [33]:
myarr.argmax(axis=0) # 컬럼별 인덱스 추출

array([1, 1, 1], dtype=int64)

In [34]:
myarr.argmax(axis=1) # 로우별 인덱스 추출

array([2, 2], dtype=int64)