In [1]:
import tensorflow as tf

In [31]:
# 1에서 7까지 임의의 숫자 10행 1열 매트릭스 생성
x = tf.random_uniform([10,2], minval=1, maxval=7, dtype=tf.int32)

In [32]:
sess = tf.Session()

In [33]:
sess.run(x )

array([[3, 1, 2],
       [4, 1, 5],
       [6, 3, 3],
       [1, 5, 5],
       [5, 1, 6],
       [6, 3, 1],
       [6, 5, 6],
       [2, 3, 5],
       [2, 3, 6],
       [2, 3, 5]])

In [12]:
# concat ; tensor 결합

c = tf.constant([[1],[2]])
d = tf.constant([[3],[4]])
r = tf.concat([c,d] , axis = 0) # 행으로 결합
r = tf.concat([c,d] , axis = 1) # 열로 결합

In [13]:
sess.run(r)

array([[1, 3],
       [2, 4]])

In [41]:
# 주사위 2개를 10번 굴리기를 시행했을 때
# 10 X 3 매트릭스 텐서를 생성하시오
# 1열과 2열은 주사위를 시행했을 때 값이며
# 3열은 두개의 열의 합으로 구성된다

x = tf.random_uniform([10,1], minval=1, maxval=7, dtype=tf.int32)
y = tf.random_uniform([10,1], minval=1, maxval=7, dtype=tf.int32)
z = x + y  # dsum = tf.add(x,y)
r = tf.concat([x,y,z] , axis = 1)

sess = tf.Session()
sess.run( r )


array([[ 6,  1,  7],
       [ 6,  2,  8],
       [ 2,  1,  3],
       [ 1,  4,  5],
       [ 4,  5,  9],
       [ 4,  6, 10],
       [ 2,  1,  3],
       [ 6,  2,  8],
       [ 3,  3,  6],
       [ 5,  6, 11]])