In [1]:
import tensorflow as tf

In [2]:
a = tf.constant( [10,20] ) # 벡터
b = tf.constant([1,2])


In [3]:
c = tf.subtract( a,b ) # a-b

In [4]:
sess = tf.Session()

In [6]:
sess.run( c ) # element wise(요소별 연산), numpy에서랑 유사

array([ 9, 18])

In [7]:
d = tf.mod(a,b) # a % b랑 같은 연산

In [9]:
sess.run( d ) # element wise, 나머지 도출

array([0, 0])

In [10]:
e = tf.divide( a,b )

In [11]:
sess.run(e) # element wise, 몫 도출

array([10., 10.])