In [3]:
import tensorflow as tf

In [22]:
a = tf.constant([ [1,2,3], [4,5,6] ] )
# b = tf.constant( [10] )
# b = tf.constant( [[10, 11]] ) broad casting이 안됨
# b = tf.constant( [10], [11] ) broad casting 가능 10 10 10 / 11 11 11로 연산됨
b = tf.constant( [10,11,12])

In [18]:
c = a + b # tf.add(a,b)

In [19]:
sess = tf.Session()

In [21]:
sess.run( c ) # element wise
# 2행 3열

# b를 [10]으로 지정하나 10으로 지정하나 연산결과가 같음
# broad casting?

array([[11, 13, 15],
       [14, 16, 18]])

In [23]:
x = tf.constant( [[1,2], [3,4]] )
y = tf.constant( [[5,6], [7,8]] )

In [26]:
# x,y 가 반드시 매트릭스여야 함
# 대부분의 다른 연산은 element wise이지만
# matmul은 매트릭스 연산임-> 브로드 캐스팅 안됨
z = tf.matmul( x,y )


<tf.Tensor 'MatMul_2:0' shape=(2, 2) dtype=int32>

In [27]:
sess.run( z )

array([[19, 22],
       [43, 50]])

In [28]:
# 곱하기
y = tf.multiply ( x,y )

In [29]:
sess.run(y)
# element wise, 브로드캐스팅 다 된다

array([[ 5, 12],
       [21, 32]])